author: Chromium Authors <mojo-dev@googlegroups.com>
dependencies:
  mojo_sdk: 0.2.29
  test: ^0.12.6+1
description: Test harness for mojo applications
environment:
  sdk: '>=1.9.0 <2.0.0'
homepage: https://github.com/domokit/mojo
name: mojo_apptest
version: 0.2.33
