author: Chromium Authors <mojo-dev@googlegroups.com>
dependencies:
  args: '>=0.13.0 <1.0.0'
  crypto: '>=0.9.0 <1.0.0'
  logging: '>=0.11.0 <1.0.0'
  mojo_sdk: 0.2.29
  path: '>=1.3.5 <2.0.0'
  yaml: ^2.1.8
description: Placeholder for mojom bindings.
dev_dependencies:
  unittest: '>=0.11.5+4 <0.12.0'
environment:
  sdk: '>=1.9.0 <2.0.0'
homepage: https://github.com/domokit/mojo
name: mojom
version: 0.2.33
