// WARNING: DO NOT EDIT. This file was generated by a program.
// See $MOJO_SDK/tools/bindings/mojom_bindings_generator.py.

library file_mojom;
import 'dart:async';
import 'package:mojo/bindings.dart' as bindings;
import 'package:mojo/core.dart' as core;
import 'package:mojo/mojo/bindings/types/service_describer.mojom.dart' as service_describer;
import 'package:mojo_services/mojo/files/types.mojom.dart' as types_mojom;



class _FileCloseParams extends bindings.Struct {
  static const List<bindings.StructDataHeader> kVersions = const [
    const bindings.StructDataHeader(8, 0)
  ];

  _FileCloseParams() : super(kVersions.last.size);

  _FileCloseParams.init(
  ) : super(kVersions.last.size);

  static _FileCloseParams deserialize(bindings.Message message) =>
      bindings.Struct.deserialize(decode, message);

  static _FileCloseParams decode(bindings.Decoder decoder0) {
    if (decoder0 == null) {
      return null;
    }
    _FileCloseParams result = new _FileCloseParams();

    var mainDataHeader = bindings.Struct.checkVersion(decoder0, kVersions);
    return result;
  }

  void encode(bindings.Encoder encoder) {
    encoder.getStructEncoderAtOffset(kVersions.last);
    const String structName = "_FileCloseParams";
    String fieldName;
    try {
    } on bindings.MojoCodecError catch(e) {
      bindings.Struct.fixErrorMessage(e, fieldName, structName);
      rethrow;
    }
  }

  String toString() {
    return "_FileCloseParams("")";
  }

  Map toJson() {
    Map map = new Map();
    return map;
  }
}


class FileCloseResponseParams extends bindings.Struct {
  static const List<bindings.StructDataHeader> kVersions = const [
    const bindings.StructDataHeader(16, 0)
  ];
  types_mojom.Error err = null;

  FileCloseResponseParams() : super(kVersions.last.size);

  FileCloseResponseParams.init(
    types_mojom.Error this.err
  ) : super(kVersions.last.size);

  static FileCloseResponseParams deserialize(bindings.Message message) =>
      bindings.Struct.deserialize(decode, message);

  static FileCloseResponseParams decode(bindings.Decoder decoder0) {
    if (decoder0 == null) {
      return null;
    }
    FileCloseResponseParams result = new FileCloseResponseParams();

    var mainDataHeader = bindings.Struct.checkVersion(decoder0, kVersions);
    if (mainDataHeader.version >= 0) {
      
        result.err = types_mojom.Error.decode(decoder0, 8);
        if (result.err == null) {
          throw new bindings.MojoCodecError(
            'Trying to decode null union for non-nullable types_mojom.Error.');
        }
    }
    return result;
  }

  void encode(bindings.Encoder encoder) {
    var encoder0 = encoder.getStructEncoderAtOffset(kVersions.last);
    const String structName = "FileCloseResponseParams";
    String fieldName;
    try {
      fieldName = "err";
      encoder0.encodeEnum(err, 8);
    } on bindings.MojoCodecError catch(e) {
      bindings.Struct.fixErrorMessage(e, fieldName, structName);
      rethrow;
    }
  }

  String toString() {
    return "FileCloseResponseParams("
           "err: $err" ")";
  }

  Map toJson() {
    Map map = new Map();
    map["err"] = err;
    return map;
  }
}


class _FileReadParams extends bindings.Struct {
  static const List<bindings.StructDataHeader> kVersions = const [
    const bindings.StructDataHeader(24, 0)
  ];
  int numBytesToRead = 0;
  types_mojom.Whence whence = null;
  int offset = 0;

  _FileReadParams() : super(kVersions.last.size);

  _FileReadParams.init(
    int this.numBytesToRead, 
    types_mojom.Whence this.whence, 
    int this.offset
  ) : super(kVersions.last.size);

  static _FileReadParams deserialize(bindings.Message message) =>
      bindings.Struct.deserialize(decode, message);

  static _FileReadParams decode(bindings.Decoder decoder0) {
    if (decoder0 == null) {
      return null;
    }
    _FileReadParams result = new _FileReadParams();

    var mainDataHeader = bindings.Struct.checkVersion(decoder0, kVersions);
    if (mainDataHeader.version >= 0) {
      
      result.numBytesToRead = decoder0.decodeUint32(8);
    }
    if (mainDataHeader.version >= 0) {
      
        result.whence = types_mojom.Whence.decode(decoder0, 12);
        if (result.whence == null) {
          throw new bindings.MojoCodecError(
            'Trying to decode null union for non-nullable types_mojom.Whence.');
        }
    }
    if (mainDataHeader.version >= 0) {
      
      result.offset = decoder0.decodeInt64(16);
    }
    return result;
  }

  void encode(bindings.Encoder encoder) {
    var encoder0 = encoder.getStructEncoderAtOffset(kVersions.last);
    const String structName = "_FileReadParams";
    String fieldName;
    try {
      fieldName = "numBytesToRead";
      encoder0.encodeUint32(numBytesToRead, 8);
      fieldName = "whence";
      encoder0.encodeEnum(whence, 12);
      fieldName = "offset";
      encoder0.encodeInt64(offset, 16);
    } on bindings.MojoCodecError catch(e) {
      bindings.Struct.fixErrorMessage(e, fieldName, structName);
      rethrow;
    }
  }

  String toString() {
    return "_FileReadParams("
           "numBytesToRead: $numBytesToRead" ", "
           "whence: $whence" ", "
           "offset: $offset" ")";
  }

  Map toJson() {
    Map map = new Map();
    map["numBytesToRead"] = numBytesToRead;
    map["whence"] = whence;
    map["offset"] = offset;
    return map;
  }
}


class FileReadResponseParams extends bindings.Struct {
  static const List<bindings.StructDataHeader> kVersions = const [
    const bindings.StructDataHeader(24, 0)
  ];
  types_mojom.Error error = null;
  List<int> bytesRead = null;

  FileReadResponseParams() : super(kVersions.last.size);

  FileReadResponseParams.init(
    types_mojom.Error this.error, 
    List<int> this.bytesRead
  ) : super(kVersions.last.size);

  static FileReadResponseParams deserialize(bindings.Message message) =>
      bindings.Struct.deserialize(decode, message);

  static FileReadResponseParams decode(bindings.Decoder decoder0) {
    if (decoder0 == null) {
      return null;
    }
    FileReadResponseParams result = new FileReadResponseParams();

    var mainDataHeader = bindings.Struct.checkVersion(decoder0, kVersions);
    if (mainDataHeader.version >= 0) {
      
        result.error = types_mojom.Error.decode(decoder0, 8);
        if (result.error == null) {
          throw new bindings.MojoCodecError(
            'Trying to decode null union for non-nullable types_mojom.Error.');
        }
    }
    if (mainDataHeader.version >= 0) {
      
      result.bytesRead = decoder0.decodeUint8Array(16, bindings.kArrayNullable, bindings.kUnspecifiedArrayLength);
    }
    return result;
  }

  void encode(bindings.Encoder encoder) {
    var encoder0 = encoder.getStructEncoderAtOffset(kVersions.last);
    const String structName = "FileReadResponseParams";
    String fieldName;
    try {
      fieldName = "error";
      encoder0.encodeEnum(error, 8);
      fieldName = "bytesRead";
      encoder0.encodeUint8Array(bytesRead, 16, bindings.kArrayNullable, bindings.kUnspecifiedArrayLength);
    } on bindings.MojoCodecError catch(e) {
      bindings.Struct.fixErrorMessage(e, fieldName, structName);
      rethrow;
    }
  }

  String toString() {
    return "FileReadResponseParams("
           "error: $error" ", "
           "bytesRead: $bytesRead" ")";
  }

  Map toJson() {
    Map map = new Map();
    map["error"] = error;
    map["bytesRead"] = bytesRead;
    return map;
  }
}


class _FileWriteParams extends bindings.Struct {
  static const List<bindings.StructDataHeader> kVersions = const [
    const bindings.StructDataHeader(32, 0)
  ];
  List<int> bytesToWrite = null;
  int offset = 0;
  types_mojom.Whence whence = null;

  _FileWriteParams() : super(kVersions.last.size);

  _FileWriteParams.init(
    List<int> this.bytesToWrite, 
    int this.offset, 
    types_mojom.Whence this.whence
  ) : super(kVersions.last.size);

  static _FileWriteParams deserialize(bindings.Message message) =>
      bindings.Struct.deserialize(decode, message);

  static _FileWriteParams decode(bindings.Decoder decoder0) {
    if (decoder0 == null) {
      return null;
    }
    _FileWriteParams result = new _FileWriteParams();

    var mainDataHeader = bindings.Struct.checkVersion(decoder0, kVersions);
    if (mainDataHeader.version >= 0) {
      
      result.bytesToWrite = decoder0.decodeUint8Array(8, bindings.kNothingNullable, bindings.kUnspecifiedArrayLength);
    }
    if (mainDataHeader.version >= 0) {
      
      result.offset = decoder0.decodeInt64(16);
    }
    if (mainDataHeader.version >= 0) {
      
        result.whence = types_mojom.Whence.decode(decoder0, 24);
        if (result.whence == null) {
          throw new bindings.MojoCodecError(
            'Trying to decode null union for non-nullable types_mojom.Whence.');
        }
    }
    return result;
  }

  void encode(bindings.Encoder encoder) {
    var encoder0 = encoder.getStructEncoderAtOffset(kVersions.last);
    const String structName = "_FileWriteParams";
    String fieldName;
    try {
      fieldName = "bytesToWrite";
      encoder0.encodeUint8Array(bytesToWrite, 8, bindings.kNothingNullable, bindings.kUnspecifiedArrayLength);
      fieldName = "offset";
      encoder0.encodeInt64(offset, 16);
      fieldName = "whence";
      encoder0.encodeEnum(whence, 24);
    } on bindings.MojoCodecError catch(e) {
      bindings.Struct.fixErrorMessage(e, fieldName, structName);
      rethrow;
    }
  }

  String toString() {
    return "_FileWriteParams("
           "bytesToWrite: $bytesToWrite" ", "
           "offset: $offset" ", "
           "whence: $whence" ")";
  }

  Map toJson() {
    Map map = new Map();
    map["bytesToWrite"] = bytesToWrite;
    map["offset"] = offset;
    map["whence"] = whence;
    return map;
  }
}


class FileWriteResponseParams extends bindings.Struct {
  static const List<bindings.StructDataHeader> kVersions = const [
    const bindings.StructDataHeader(16, 0)
  ];
  types_mojom.Error error = null;
  int numBytesWritten = 0;

  FileWriteResponseParams() : super(kVersions.last.size);

  FileWriteResponseParams.init(
    types_mojom.Error this.error, 
    int this.numBytesWritten
  ) : super(kVersions.last.size);

  static FileWriteResponseParams deserialize(bindings.Message message) =>
      bindings.Struct.deserialize(decode, message);

  static FileWriteResponseParams decode(bindings.Decoder decoder0) {
    if (decoder0 == null) {
      return null;
    }
    FileWriteResponseParams result = new FileWriteResponseParams();

    var mainDataHeader = bindings.Struct.checkVersion(decoder0, kVersions);
    if (mainDataHeader.version >= 0) {
      
        result.error = types_mojom.Error.decode(decoder0, 8);
        if (result.error == null) {
          throw new bindings.MojoCodecError(
            'Trying to decode null union for non-nullable types_mojom.Error.');
        }
    }
    if (mainDataHeader.version >= 0) {
      
      result.numBytesWritten = decoder0.decodeUint32(12);
    }
    return result;
  }

  void encode(bindings.Encoder encoder) {
    var encoder0 = encoder.getStructEncoderAtOffset(kVersions.last);
    const String structName = "FileWriteResponseParams";
    String fieldName;
    try {
      fieldName = "error";
      encoder0.encodeEnum(error, 8);
      fieldName = "numBytesWritten";
      encoder0.encodeUint32(numBytesWritten, 12);
    } on bindings.MojoCodecError catch(e) {
      bindings.Struct.fixErrorMessage(e, fieldName, structName);
      rethrow;
    }
  }

  String toString() {
    return "FileWriteResponseParams("
           "error: $error" ", "
           "numBytesWritten: $numBytesWritten" ")";
  }

  Map toJson() {
    Map map = new Map();
    map["error"] = error;
    map["numBytesWritten"] = numBytesWritten;
    return map;
  }
}


class _FileReadToStreamParams extends bindings.Struct {
  static const List<bindings.StructDataHeader> kVersions = const [
    const bindings.StructDataHeader(32, 0)
  ];
  core.MojoDataPipeProducer source = null;
  types_mojom.Whence whence = null;
  int offset = 0;
  int numBytesToRead = 0;

  _FileReadToStreamParams() : super(kVersions.last.size);

  _FileReadToStreamParams.init(
    core.MojoDataPipeProducer this.source, 
    types_mojom.Whence this.whence, 
    int this.offset, 
    int this.numBytesToRead
  ) : super(kVersions.last.size);

  static _FileReadToStreamParams deserialize(bindings.Message message) =>
      bindings.Struct.deserialize(decode, message);

  static _FileReadToStreamParams decode(bindings.Decoder decoder0) {
    if (decoder0 == null) {
      return null;
    }
    _FileReadToStreamParams result = new _FileReadToStreamParams();

    var mainDataHeader = bindings.Struct.checkVersion(decoder0, kVersions);
    if (mainDataHeader.version >= 0) {
      
      result.source = decoder0.decodeProducerHandle(8, false);
    }
    if (mainDataHeader.version >= 0) {
      
        result.whence = types_mojom.Whence.decode(decoder0, 12);
        if (result.whence == null) {
          throw new bindings.MojoCodecError(
            'Trying to decode null union for non-nullable types_mojom.Whence.');
        }
    }
    if (mainDataHeader.version >= 0) {
      
      result.offset = decoder0.decodeInt64(16);
    }
    if (mainDataHeader.version >= 0) {
      
      result.numBytesToRead = decoder0.decodeInt64(24);
    }
    return result;
  }

  void encode(bindings.Encoder encoder) {
    var encoder0 = encoder.getStructEncoderAtOffset(kVersions.last);
    const String structName = "_FileReadToStreamParams";
    String fieldName;
    try {
      fieldName = "source";
      encoder0.encodeProducerHandle(source, 8, false);
      fieldName = "whence";
      encoder0.encodeEnum(whence, 12);
      fieldName = "offset";
      encoder0.encodeInt64(offset, 16);
      fieldName = "numBytesToRead";
      encoder0.encodeInt64(numBytesToRead, 24);
    } on bindings.MojoCodecError catch(e) {
      bindings.Struct.fixErrorMessage(e, fieldName, structName);
      rethrow;
    }
  }

  String toString() {
    return "_FileReadToStreamParams("
           "source: $source" ", "
           "whence: $whence" ", "
           "offset: $offset" ", "
           "numBytesToRead: $numBytesToRead" ")";
  }

  Map toJson() {
    throw new bindings.MojoCodecError(
        'Object containing handles cannot be encoded to JSON.');
  }
}


class FileReadToStreamResponseParams extends bindings.Struct {
  static const List<bindings.StructDataHeader> kVersions = const [
    const bindings.StructDataHeader(16, 0)
  ];
  types_mojom.Error error = null;

  FileReadToStreamResponseParams() : super(kVersions.last.size);

  FileReadToStreamResponseParams.init(
    types_mojom.Error this.error
  ) : super(kVersions.last.size);

  static FileReadToStreamResponseParams deserialize(bindings.Message message) =>
      bindings.Struct.deserialize(decode, message);

  static FileReadToStreamResponseParams decode(bindings.Decoder decoder0) {
    if (decoder0 == null) {
      return null;
    }
    FileReadToStreamResponseParams result = new FileReadToStreamResponseParams();

    var mainDataHeader = bindings.Struct.checkVersion(decoder0, kVersions);
    if (mainDataHeader.version >= 0) {
      
        result.error = types_mojom.Error.decode(decoder0, 8);
        if (result.error == null) {
          throw new bindings.MojoCodecError(
            'Trying to decode null union for non-nullable types_mojom.Error.');
        }
    }
    return result;
  }

  void encode(bindings.Encoder encoder) {
    var encoder0 = encoder.getStructEncoderAtOffset(kVersions.last);
    const String structName = "FileReadToStreamResponseParams";
    String fieldName;
    try {
      fieldName = "error";
      encoder0.encodeEnum(error, 8);
    } on bindings.MojoCodecError catch(e) {
      bindings.Struct.fixErrorMessage(e, fieldName, structName);
      rethrow;
    }
  }

  String toString() {
    return "FileReadToStreamResponseParams("
           "error: $error" ")";
  }

  Map toJson() {
    Map map = new Map();
    map["error"] = error;
    return map;
  }
}


class _FileWriteFromStreamParams extends bindings.Struct {
  static const List<bindings.StructDataHeader> kVersions = const [
    const bindings.StructDataHeader(24, 0)
  ];
  core.MojoDataPipeConsumer sink = null;
  types_mojom.Whence whence = null;
  int offset = 0;

  _FileWriteFromStreamParams() : super(kVersions.last.size);

  _FileWriteFromStreamParams.init(
    core.MojoDataPipeConsumer this.sink, 
    types_mojom.Whence this.whence, 
    int this.offset
  ) : super(kVersions.last.size);

  static _FileWriteFromStreamParams deserialize(bindings.Message message) =>
      bindings.Struct.deserialize(decode, message);

  static _FileWriteFromStreamParams decode(bindings.Decoder decoder0) {
    if (decoder0 == null) {
      return null;
    }
    _FileWriteFromStreamParams result = new _FileWriteFromStreamParams();

    var mainDataHeader = bindings.Struct.checkVersion(decoder0, kVersions);
    if (mainDataHeader.version >= 0) {
      
      result.sink = decoder0.decodeConsumerHandle(8, false);
    }
    if (mainDataHeader.version >= 0) {
      
        result.whence = types_mojom.Whence.decode(decoder0, 12);
        if (result.whence == null) {
          throw new bindings.MojoCodecError(
            'Trying to decode null union for non-nullable types_mojom.Whence.');
        }
    }
    if (mainDataHeader.version >= 0) {
      
      result.offset = decoder0.decodeInt64(16);
    }
    return result;
  }

  void encode(bindings.Encoder encoder) {
    var encoder0 = encoder.getStructEncoderAtOffset(kVersions.last);
    const String structName = "_FileWriteFromStreamParams";
    String fieldName;
    try {
      fieldName = "sink";
      encoder0.encodeConsumerHandle(sink, 8, false);
      fieldName = "whence";
      encoder0.encodeEnum(whence, 12);
      fieldName = "offset";
      encoder0.encodeInt64(offset, 16);
    } on bindings.MojoCodecError catch(e) {
      bindings.Struct.fixErrorMessage(e, fieldName, structName);
      rethrow;
    }
  }

  String toString() {
    return "_FileWriteFromStreamParams("
           "sink: $sink" ", "
           "whence: $whence" ", "
           "offset: $offset" ")";
  }

  Map toJson() {
    throw new bindings.MojoCodecError(
        'Object containing handles cannot be encoded to JSON.');
  }
}


class FileWriteFromStreamResponseParams extends bindings.Struct {
  static const List<bindings.StructDataHeader> kVersions = const [
    const bindings.StructDataHeader(16, 0)
  ];
  types_mojom.Error error = null;

  FileWriteFromStreamResponseParams() : super(kVersions.last.size);

  FileWriteFromStreamResponseParams.init(
    types_mojom.Error this.error
  ) : super(kVersions.last.size);

  static FileWriteFromStreamResponseParams deserialize(bindings.Message message) =>
      bindings.Struct.deserialize(decode, message);

  static FileWriteFromStreamResponseParams decode(bindings.Decoder decoder0) {
    if (decoder0 == null) {
      return null;
    }
    FileWriteFromStreamResponseParams result = new FileWriteFromStreamResponseParams();

    var mainDataHeader = bindings.Struct.checkVersion(decoder0, kVersions);
    if (mainDataHeader.version >= 0) {
      
        result.error = types_mojom.Error.decode(decoder0, 8);
        if (result.error == null) {
          throw new bindings.MojoCodecError(
            'Trying to decode null union for non-nullable types_mojom.Error.');
        }
    }
    return result;
  }

  void encode(bindings.Encoder encoder) {
    var encoder0 = encoder.getStructEncoderAtOffset(kVersions.last);
    const String structName = "FileWriteFromStreamResponseParams";
    String fieldName;
    try {
      fieldName = "error";
      encoder0.encodeEnum(error, 8);
    } on bindings.MojoCodecError catch(e) {
      bindings.Struct.fixErrorMessage(e, fieldName, structName);
      rethrow;
    }
  }

  String toString() {
    return "FileWriteFromStreamResponseParams("
           "error: $error" ")";
  }

  Map toJson() {
    Map map = new Map();
    map["error"] = error;
    return map;
  }
}


class _FileTellParams extends bindings.Struct {
  static const List<bindings.StructDataHeader> kVersions = const [
    const bindings.StructDataHeader(8, 0)
  ];

  _FileTellParams() : super(kVersions.last.size);

  _FileTellParams.init(
  ) : super(kVersions.last.size);

  static _FileTellParams deserialize(bindings.Message message) =>
      bindings.Struct.deserialize(decode, message);

  static _FileTellParams decode(bindings.Decoder decoder0) {
    if (decoder0 == null) {
      return null;
    }
    _FileTellParams result = new _FileTellParams();

    var mainDataHeader = bindings.Struct.checkVersion(decoder0, kVersions);
    return result;
  }

  void encode(bindings.Encoder encoder) {
    encoder.getStructEncoderAtOffset(kVersions.last);
    const String structName = "_FileTellParams";
    String fieldName;
    try {
    } on bindings.MojoCodecError catch(e) {
      bindings.Struct.fixErrorMessage(e, fieldName, structName);
      rethrow;
    }
  }

  String toString() {
    return "_FileTellParams("")";
  }

  Map toJson() {
    Map map = new Map();
    return map;
  }
}


class FileTellResponseParams extends bindings.Struct {
  static const List<bindings.StructDataHeader> kVersions = const [
    const bindings.StructDataHeader(24, 0)
  ];
  types_mojom.Error error = null;
  int position = 0;

  FileTellResponseParams() : super(kVersions.last.size);

  FileTellResponseParams.init(
    types_mojom.Error this.error, 
    int this.position
  ) : super(kVersions.last.size);

  static FileTellResponseParams deserialize(bindings.Message message) =>
      bindings.Struct.deserialize(decode, message);

  static FileTellResponseParams decode(bindings.Decoder decoder0) {
    if (decoder0 == null) {
      return null;
    }
    FileTellResponseParams result = new FileTellResponseParams();

    var mainDataHeader = bindings.Struct.checkVersion(decoder0, kVersions);
    if (mainDataHeader.version >= 0) {
      
        result.error = types_mojom.Error.decode(decoder0, 8);
        if (result.error == null) {
          throw new bindings.MojoCodecError(
            'Trying to decode null union for non-nullable types_mojom.Error.');
        }
    }
    if (mainDataHeader.version >= 0) {
      
      result.position = decoder0.decodeInt64(16);
    }
    return result;
  }

  void encode(bindings.Encoder encoder) {
    var encoder0 = encoder.getStructEncoderAtOffset(kVersions.last);
    const String structName = "FileTellResponseParams";
    String fieldName;
    try {
      fieldName = "error";
      encoder0.encodeEnum(error, 8);
      fieldName = "position";
      encoder0.encodeInt64(position, 16);
    } on bindings.MojoCodecError catch(e) {
      bindings.Struct.fixErrorMessage(e, fieldName, structName);
      rethrow;
    }
  }

  String toString() {
    return "FileTellResponseParams("
           "error: $error" ", "
           "position: $position" ")";
  }

  Map toJson() {
    Map map = new Map();
    map["error"] = error;
    map["position"] = position;
    return map;
  }
}


class _FileSeekParams extends bindings.Struct {
  static const List<bindings.StructDataHeader> kVersions = const [
    const bindings.StructDataHeader(24, 0)
  ];
  int offset = 0;
  types_mojom.Whence whence = null;

  _FileSeekParams() : super(kVersions.last.size);

  _FileSeekParams.init(
    int this.offset, 
    types_mojom.Whence this.whence
  ) : super(kVersions.last.size);

  static _FileSeekParams deserialize(bindings.Message message) =>
      bindings.Struct.deserialize(decode, message);

  static _FileSeekParams decode(bindings.Decoder decoder0) {
    if (decoder0 == null) {
      return null;
    }
    _FileSeekParams result = new _FileSeekParams();

    var mainDataHeader = bindings.Struct.checkVersion(decoder0, kVersions);
    if (mainDataHeader.version >= 0) {
      
      result.offset = decoder0.decodeInt64(8);
    }
    if (mainDataHeader.version >= 0) {
      
        result.whence = types_mojom.Whence.decode(decoder0, 16);
        if (result.whence == null) {
          throw new bindings.MojoCodecError(
            'Trying to decode null union for non-nullable types_mojom.Whence.');
        }
    }
    return result;
  }

  void encode(bindings.Encoder encoder) {
    var encoder0 = encoder.getStructEncoderAtOffset(kVersions.last);
    const String structName = "_FileSeekParams";
    String fieldName;
    try {
      fieldName = "offset";
      encoder0.encodeInt64(offset, 8);
      fieldName = "whence";
      encoder0.encodeEnum(whence, 16);
    } on bindings.MojoCodecError catch(e) {
      bindings.Struct.fixErrorMessage(e, fieldName, structName);
      rethrow;
    }
  }

  String toString() {
    return "_FileSeekParams("
           "offset: $offset" ", "
           "whence: $whence" ")";
  }

  Map toJson() {
    Map map = new Map();
    map["offset"] = offset;
    map["whence"] = whence;
    return map;
  }
}


class FileSeekResponseParams extends bindings.Struct {
  static const List<bindings.StructDataHeader> kVersions = const [
    const bindings.StructDataHeader(24, 0)
  ];
  types_mojom.Error error = null;
  int position = 0;

  FileSeekResponseParams() : super(kVersions.last.size);

  FileSeekResponseParams.init(
    types_mojom.Error this.error, 
    int this.position
  ) : super(kVersions.last.size);

  static FileSeekResponseParams deserialize(bindings.Message message) =>
      bindings.Struct.deserialize(decode, message);

  static FileSeekResponseParams decode(bindings.Decoder decoder0) {
    if (decoder0 == null) {
      return null;
    }
    FileSeekResponseParams result = new FileSeekResponseParams();

    var mainDataHeader = bindings.Struct.checkVersion(decoder0, kVersions);
    if (mainDataHeader.version >= 0) {
      
        result.error = types_mojom.Error.decode(decoder0, 8);
        if (result.error == null) {
          throw new bindings.MojoCodecError(
            'Trying to decode null union for non-nullable types_mojom.Error.');
        }
    }
    if (mainDataHeader.version >= 0) {
      
      result.position = decoder0.decodeInt64(16);
    }
    return result;
  }

  void encode(bindings.Encoder encoder) {
    var encoder0 = encoder.getStructEncoderAtOffset(kVersions.last);
    const String structName = "FileSeekResponseParams";
    String fieldName;
    try {
      fieldName = "error";
      encoder0.encodeEnum(error, 8);
      fieldName = "position";
      encoder0.encodeInt64(position, 16);
    } on bindings.MojoCodecError catch(e) {
      bindings.Struct.fixErrorMessage(e, fieldName, structName);
      rethrow;
    }
  }

  String toString() {
    return "FileSeekResponseParams("
           "error: $error" ", "
           "position: $position" ")";
  }

  Map toJson() {
    Map map = new Map();
    map["error"] = error;
    map["position"] = position;
    return map;
  }
}


class _FileStatParams extends bindings.Struct {
  static const List<bindings.StructDataHeader> kVersions = const [
    const bindings.StructDataHeader(8, 0)
  ];

  _FileStatParams() : super(kVersions.last.size);

  _FileStatParams.init(
  ) : super(kVersions.last.size);

  static _FileStatParams deserialize(bindings.Message message) =>
      bindings.Struct.deserialize(decode, message);

  static _FileStatParams decode(bindings.Decoder decoder0) {
    if (decoder0 == null) {
      return null;
    }
    _FileStatParams result = new _FileStatParams();

    var mainDataHeader = bindings.Struct.checkVersion(decoder0, kVersions);
    return result;
  }

  void encode(bindings.Encoder encoder) {
    encoder.getStructEncoderAtOffset(kVersions.last);
    const String structName = "_FileStatParams";
    String fieldName;
    try {
    } on bindings.MojoCodecError catch(e) {
      bindings.Struct.fixErrorMessage(e, fieldName, structName);
      rethrow;
    }
  }

  String toString() {
    return "_FileStatParams("")";
  }

  Map toJson() {
    Map map = new Map();
    return map;
  }
}


class FileStatResponseParams extends bindings.Struct {
  static const List<bindings.StructDataHeader> kVersions = const [
    const bindings.StructDataHeader(24, 0)
  ];
  types_mojom.Error error = null;
  types_mojom.FileInformation fileInformation = null;

  FileStatResponseParams() : super(kVersions.last.size);

  FileStatResponseParams.init(
    types_mojom.Error this.error, 
    types_mojom.FileInformation this.fileInformation
  ) : super(kVersions.last.size);

  static FileStatResponseParams deserialize(bindings.Message message) =>
      bindings.Struct.deserialize(decode, message);

  static FileStatResponseParams decode(bindings.Decoder decoder0) {
    if (decoder0 == null) {
      return null;
    }
    FileStatResponseParams result = new FileStatResponseParams();

    var mainDataHeader = bindings.Struct.checkVersion(decoder0, kVersions);
    if (mainDataHeader.version >= 0) {
      
        result.error = types_mojom.Error.decode(decoder0, 8);
        if (result.error == null) {
          throw new bindings.MojoCodecError(
            'Trying to decode null union for non-nullable types_mojom.Error.');
        }
    }
    if (mainDataHeader.version >= 0) {
      
      var decoder1 = decoder0.decodePointer(16, true);
      result.fileInformation = types_mojom.FileInformation.decode(decoder1);
    }
    return result;
  }

  void encode(bindings.Encoder encoder) {
    var encoder0 = encoder.getStructEncoderAtOffset(kVersions.last);
    const String structName = "FileStatResponseParams";
    String fieldName;
    try {
      fieldName = "error";
      encoder0.encodeEnum(error, 8);
      fieldName = "fileInformation";
      encoder0.encodeStruct(fileInformation, 16, true);
    } on bindings.MojoCodecError catch(e) {
      bindings.Struct.fixErrorMessage(e, fieldName, structName);
      rethrow;
    }
  }

  String toString() {
    return "FileStatResponseParams("
           "error: $error" ", "
           "fileInformation: $fileInformation" ")";
  }

  Map toJson() {
    Map map = new Map();
    map["error"] = error;
    map["fileInformation"] = fileInformation;
    return map;
  }
}


class _FileTruncateParams extends bindings.Struct {
  static const List<bindings.StructDataHeader> kVersions = const [
    const bindings.StructDataHeader(16, 0)
  ];
  int size = 0;

  _FileTruncateParams() : super(kVersions.last.size);

  _FileTruncateParams.init(
    int this.size
  ) : super(kVersions.last.size);

  static _FileTruncateParams deserialize(bindings.Message message) =>
      bindings.Struct.deserialize(decode, message);

  static _FileTruncateParams decode(bindings.Decoder decoder0) {
    if (decoder0 == null) {
      return null;
    }
    _FileTruncateParams result = new _FileTruncateParams();

    var mainDataHeader = bindings.Struct.checkVersion(decoder0, kVersions);
    if (mainDataHeader.version >= 0) {
      
      result.size = decoder0.decodeInt64(8);
    }
    return result;
  }

  void encode(bindings.Encoder encoder) {
    var encoder0 = encoder.getStructEncoderAtOffset(kVersions.last);
    const String structName = "_FileTruncateParams";
    String fieldName;
    try {
      fieldName = "size";
      encoder0.encodeInt64(size, 8);
    } on bindings.MojoCodecError catch(e) {
      bindings.Struct.fixErrorMessage(e, fieldName, structName);
      rethrow;
    }
  }

  String toString() {
    return "_FileTruncateParams("
           "size: $size" ")";
  }

  Map toJson() {
    Map map = new Map();
    map["size"] = size;
    return map;
  }
}


class FileTruncateResponseParams extends bindings.Struct {
  static const List<bindings.StructDataHeader> kVersions = const [
    const bindings.StructDataHeader(16, 0)
  ];
  types_mojom.Error error = null;

  FileTruncateResponseParams() : super(kVersions.last.size);

  FileTruncateResponseParams.init(
    types_mojom.Error this.error
  ) : super(kVersions.last.size);

  static FileTruncateResponseParams deserialize(bindings.Message message) =>
      bindings.Struct.deserialize(decode, message);

  static FileTruncateResponseParams decode(bindings.Decoder decoder0) {
    if (decoder0 == null) {
      return null;
    }
    FileTruncateResponseParams result = new FileTruncateResponseParams();

    var mainDataHeader = bindings.Struct.checkVersion(decoder0, kVersions);
    if (mainDataHeader.version >= 0) {
      
        result.error = types_mojom.Error.decode(decoder0, 8);
        if (result.error == null) {
          throw new bindings.MojoCodecError(
            'Trying to decode null union for non-nullable types_mojom.Error.');
        }
    }
    return result;
  }

  void encode(bindings.Encoder encoder) {
    var encoder0 = encoder.getStructEncoderAtOffset(kVersions.last);
    const String structName = "FileTruncateResponseParams";
    String fieldName;
    try {
      fieldName = "error";
      encoder0.encodeEnum(error, 8);
    } on bindings.MojoCodecError catch(e) {
      bindings.Struct.fixErrorMessage(e, fieldName, structName);
      rethrow;
    }
  }

  String toString() {
    return "FileTruncateResponseParams("
           "error: $error" ")";
  }

  Map toJson() {
    Map map = new Map();
    map["error"] = error;
    return map;
  }
}


class _FileTouchParams extends bindings.Struct {
  static const List<bindings.StructDataHeader> kVersions = const [
    const bindings.StructDataHeader(24, 0)
  ];
  types_mojom.TimespecOrNow atime = null;
  types_mojom.TimespecOrNow mtime = null;

  _FileTouchParams() : super(kVersions.last.size);

  _FileTouchParams.init(
    types_mojom.TimespecOrNow this.atime, 
    types_mojom.TimespecOrNow this.mtime
  ) : super(kVersions.last.size);

  static _FileTouchParams deserialize(bindings.Message message) =>
      bindings.Struct.deserialize(decode, message);

  static _FileTouchParams decode(bindings.Decoder decoder0) {
    if (decoder0 == null) {
      return null;
    }
    _FileTouchParams result = new _FileTouchParams();

    var mainDataHeader = bindings.Struct.checkVersion(decoder0, kVersions);
    if (mainDataHeader.version >= 0) {
      
      var decoder1 = decoder0.decodePointer(8, true);
      result.atime = types_mojom.TimespecOrNow.decode(decoder1);
    }
    if (mainDataHeader.version >= 0) {
      
      var decoder1 = decoder0.decodePointer(16, true);
      result.mtime = types_mojom.TimespecOrNow.decode(decoder1);
    }
    return result;
  }

  void encode(bindings.Encoder encoder) {
    var encoder0 = encoder.getStructEncoderAtOffset(kVersions.last);
    const String structName = "_FileTouchParams";
    String fieldName;
    try {
      fieldName = "atime";
      encoder0.encodeStruct(atime, 8, true);
      fieldName = "mtime";
      encoder0.encodeStruct(mtime, 16, true);
    } on bindings.MojoCodecError catch(e) {
      bindings.Struct.fixErrorMessage(e, fieldName, structName);
      rethrow;
    }
  }

  String toString() {
    return "_FileTouchParams("
           "atime: $atime" ", "
           "mtime: $mtime" ")";
  }

  Map toJson() {
    Map map = new Map();
    map["atime"] = atime;
    map["mtime"] = mtime;
    return map;
  }
}


class FileTouchResponseParams extends bindings.Struct {
  static const List<bindings.StructDataHeader> kVersions = const [
    const bindings.StructDataHeader(16, 0)
  ];
  types_mojom.Error error = null;

  FileTouchResponseParams() : super(kVersions.last.size);

  FileTouchResponseParams.init(
    types_mojom.Error this.error
  ) : super(kVersions.last.size);

  static FileTouchResponseParams deserialize(bindings.Message message) =>
      bindings.Struct.deserialize(decode, message);

  static FileTouchResponseParams decode(bindings.Decoder decoder0) {
    if (decoder0 == null) {
      return null;
    }
    FileTouchResponseParams result = new FileTouchResponseParams();

    var mainDataHeader = bindings.Struct.checkVersion(decoder0, kVersions);
    if (mainDataHeader.version >= 0) {
      
        result.error = types_mojom.Error.decode(decoder0, 8);
        if (result.error == null) {
          throw new bindings.MojoCodecError(
            'Trying to decode null union for non-nullable types_mojom.Error.');
        }
    }
    return result;
  }

  void encode(bindings.Encoder encoder) {
    var encoder0 = encoder.getStructEncoderAtOffset(kVersions.last);
    const String structName = "FileTouchResponseParams";
    String fieldName;
    try {
      fieldName = "error";
      encoder0.encodeEnum(error, 8);
    } on bindings.MojoCodecError catch(e) {
      bindings.Struct.fixErrorMessage(e, fieldName, structName);
      rethrow;
    }
  }

  String toString() {
    return "FileTouchResponseParams("
           "error: $error" ")";
  }

  Map toJson() {
    Map map = new Map();
    map["error"] = error;
    return map;
  }
}


class _FileDupParams extends bindings.Struct {
  static const List<bindings.StructDataHeader> kVersions = const [
    const bindings.StructDataHeader(16, 0)
  ];
  FileInterfaceRequest file = null;

  _FileDupParams() : super(kVersions.last.size);

  _FileDupParams.init(
    FileInterfaceRequest this.file
  ) : super(kVersions.last.size);

  static _FileDupParams deserialize(bindings.Message message) =>
      bindings.Struct.deserialize(decode, message);

  static _FileDupParams decode(bindings.Decoder decoder0) {
    if (decoder0 == null) {
      return null;
    }
    _FileDupParams result = new _FileDupParams();

    var mainDataHeader = bindings.Struct.checkVersion(decoder0, kVersions);
    if (mainDataHeader.version >= 0) {
      
      result.file = decoder0.decodeInterfaceRequest(8, false, FileStub.newFromEndpoint);
    }
    return result;
  }

  void encode(bindings.Encoder encoder) {
    var encoder0 = encoder.getStructEncoderAtOffset(kVersions.last);
    const String structName = "_FileDupParams";
    String fieldName;
    try {
      fieldName = "file";
      encoder0.encodeInterfaceRequest(file, 8, false);
    } on bindings.MojoCodecError catch(e) {
      bindings.Struct.fixErrorMessage(e, fieldName, structName);
      rethrow;
    }
  }

  String toString() {
    return "_FileDupParams("
           "file: $file" ")";
  }

  Map toJson() {
    throw new bindings.MojoCodecError(
        'Object containing handles cannot be encoded to JSON.');
  }
}


class FileDupResponseParams extends bindings.Struct {
  static const List<bindings.StructDataHeader> kVersions = const [
    const bindings.StructDataHeader(16, 0)
  ];
  types_mojom.Error error = null;

  FileDupResponseParams() : super(kVersions.last.size);

  FileDupResponseParams.init(
    types_mojom.Error this.error
  ) : super(kVersions.last.size);

  static FileDupResponseParams deserialize(bindings.Message message) =>
      bindings.Struct.deserialize(decode, message);

  static FileDupResponseParams decode(bindings.Decoder decoder0) {
    if (decoder0 == null) {
      return null;
    }
    FileDupResponseParams result = new FileDupResponseParams();

    var mainDataHeader = bindings.Struct.checkVersion(decoder0, kVersions);
    if (mainDataHeader.version >= 0) {
      
        result.error = types_mojom.Error.decode(decoder0, 8);
        if (result.error == null) {
          throw new bindings.MojoCodecError(
            'Trying to decode null union for non-nullable types_mojom.Error.');
        }
    }
    return result;
  }

  void encode(bindings.Encoder encoder) {
    var encoder0 = encoder.getStructEncoderAtOffset(kVersions.last);
    const String structName = "FileDupResponseParams";
    String fieldName;
    try {
      fieldName = "error";
      encoder0.encodeEnum(error, 8);
    } on bindings.MojoCodecError catch(e) {
      bindings.Struct.fixErrorMessage(e, fieldName, structName);
      rethrow;
    }
  }

  String toString() {
    return "FileDupResponseParams("
           "error: $error" ")";
  }

  Map toJson() {
    Map map = new Map();
    map["error"] = error;
    return map;
  }
}


class _FileReopenParams extends bindings.Struct {
  static const List<bindings.StructDataHeader> kVersions = const [
    const bindings.StructDataHeader(16, 0)
  ];
  FileInterfaceRequest file = null;
  int openFlags = 0;

  _FileReopenParams() : super(kVersions.last.size);

  _FileReopenParams.init(
    FileInterfaceRequest this.file, 
    int this.openFlags
  ) : super(kVersions.last.size);

  static _FileReopenParams deserialize(bindings.Message message) =>
      bindings.Struct.deserialize(decode, message);

  static _FileReopenParams decode(bindings.Decoder decoder0) {
    if (decoder0 == null) {
      return null;
    }
    _FileReopenParams result = new _FileReopenParams();

    var mainDataHeader = bindings.Struct.checkVersion(decoder0, kVersions);
    if (mainDataHeader.version >= 0) {
      
      result.file = decoder0.decodeInterfaceRequest(8, false, FileStub.newFromEndpoint);
    }
    if (mainDataHeader.version >= 0) {
      
      result.openFlags = decoder0.decodeUint32(12);
    }
    return result;
  }

  void encode(bindings.Encoder encoder) {
    var encoder0 = encoder.getStructEncoderAtOffset(kVersions.last);
    const String structName = "_FileReopenParams";
    String fieldName;
    try {
      fieldName = "file";
      encoder0.encodeInterfaceRequest(file, 8, false);
      fieldName = "openFlags";
      encoder0.encodeUint32(openFlags, 12);
    } on bindings.MojoCodecError catch(e) {
      bindings.Struct.fixErrorMessage(e, fieldName, structName);
      rethrow;
    }
  }

  String toString() {
    return "_FileReopenParams("
           "file: $file" ", "
           "openFlags: $openFlags" ")";
  }

  Map toJson() {
    throw new bindings.MojoCodecError(
        'Object containing handles cannot be encoded to JSON.');
  }
}


class FileReopenResponseParams extends bindings.Struct {
  static const List<bindings.StructDataHeader> kVersions = const [
    const bindings.StructDataHeader(16, 0)
  ];
  types_mojom.Error error = null;

  FileReopenResponseParams() : super(kVersions.last.size);

  FileReopenResponseParams.init(
    types_mojom.Error this.error
  ) : super(kVersions.last.size);

  static FileReopenResponseParams deserialize(bindings.Message message) =>
      bindings.Struct.deserialize(decode, message);

  static FileReopenResponseParams decode(bindings.Decoder decoder0) {
    if (decoder0 == null) {
      return null;
    }
    FileReopenResponseParams result = new FileReopenResponseParams();

    var mainDataHeader = bindings.Struct.checkVersion(decoder0, kVersions);
    if (mainDataHeader.version >= 0) {
      
        result.error = types_mojom.Error.decode(decoder0, 8);
        if (result.error == null) {
          throw new bindings.MojoCodecError(
            'Trying to decode null union for non-nullable types_mojom.Error.');
        }
    }
    return result;
  }

  void encode(bindings.Encoder encoder) {
    var encoder0 = encoder.getStructEncoderAtOffset(kVersions.last);
    const String structName = "FileReopenResponseParams";
    String fieldName;
    try {
      fieldName = "error";
      encoder0.encodeEnum(error, 8);
    } on bindings.MojoCodecError catch(e) {
      bindings.Struct.fixErrorMessage(e, fieldName, structName);
      rethrow;
    }
  }

  String toString() {
    return "FileReopenResponseParams("
           "error: $error" ")";
  }

  Map toJson() {
    Map map = new Map();
    map["error"] = error;
    return map;
  }
}


class _FileAsBufferParams extends bindings.Struct {
  static const List<bindings.StructDataHeader> kVersions = const [
    const bindings.StructDataHeader(8, 0)
  ];

  _FileAsBufferParams() : super(kVersions.last.size);

  _FileAsBufferParams.init(
  ) : super(kVersions.last.size);

  static _FileAsBufferParams deserialize(bindings.Message message) =>
      bindings.Struct.deserialize(decode, message);

  static _FileAsBufferParams decode(bindings.Decoder decoder0) {
    if (decoder0 == null) {
      return null;
    }
    _FileAsBufferParams result = new _FileAsBufferParams();

    var mainDataHeader = bindings.Struct.checkVersion(decoder0, kVersions);
    return result;
  }

  void encode(bindings.Encoder encoder) {
    encoder.getStructEncoderAtOffset(kVersions.last);
    const String structName = "_FileAsBufferParams";
    String fieldName;
    try {
    } on bindings.MojoCodecError catch(e) {
      bindings.Struct.fixErrorMessage(e, fieldName, structName);
      rethrow;
    }
  }

  String toString() {
    return "_FileAsBufferParams("")";
  }

  Map toJson() {
    Map map = new Map();
    return map;
  }
}


class FileAsBufferResponseParams extends bindings.Struct {
  static const List<bindings.StructDataHeader> kVersions = const [
    const bindings.StructDataHeader(16, 0)
  ];
  types_mojom.Error error = null;
  core.MojoSharedBuffer buffer = null;

  FileAsBufferResponseParams() : super(kVersions.last.size);

  FileAsBufferResponseParams.init(
    types_mojom.Error this.error, 
    core.MojoSharedBuffer this.buffer
  ) : super(kVersions.last.size);

  static FileAsBufferResponseParams deserialize(bindings.Message message) =>
      bindings.Struct.deserialize(decode, message);

  static FileAsBufferResponseParams decode(bindings.Decoder decoder0) {
    if (decoder0 == null) {
      return null;
    }
    FileAsBufferResponseParams result = new FileAsBufferResponseParams();

    var mainDataHeader = bindings.Struct.checkVersion(decoder0, kVersions);
    if (mainDataHeader.version >= 0) {
      
        result.error = types_mojom.Error.decode(decoder0, 8);
        if (result.error == null) {
          throw new bindings.MojoCodecError(
            'Trying to decode null union for non-nullable types_mojom.Error.');
        }
    }
    if (mainDataHeader.version >= 0) {
      
      result.buffer = decoder0.decodeSharedBufferHandle(12, true);
    }
    return result;
  }

  void encode(bindings.Encoder encoder) {
    var encoder0 = encoder.getStructEncoderAtOffset(kVersions.last);
    const String structName = "FileAsBufferResponseParams";
    String fieldName;
    try {
      fieldName = "error";
      encoder0.encodeEnum(error, 8);
      fieldName = "buffer";
      encoder0.encodeSharedBufferHandle(buffer, 12, true);
    } on bindings.MojoCodecError catch(e) {
      bindings.Struct.fixErrorMessage(e, fieldName, structName);
      rethrow;
    }
  }

  String toString() {
    return "FileAsBufferResponseParams("
           "error: $error" ", "
           "buffer: $buffer" ")";
  }

  Map toJson() {
    throw new bindings.MojoCodecError(
        'Object containing handles cannot be encoded to JSON.');
  }
}


class _FileIoctlParams extends bindings.Struct {
  static const List<bindings.StructDataHeader> kVersions = const [
    const bindings.StructDataHeader(24, 0)
  ];
  int request = 0;
  List<int> inValues = null;

  _FileIoctlParams() : super(kVersions.last.size);

  _FileIoctlParams.init(
    int this.request, 
    List<int> this.inValues
  ) : super(kVersions.last.size);

  static _FileIoctlParams deserialize(bindings.Message message) =>
      bindings.Struct.deserialize(decode, message);

  static _FileIoctlParams decode(bindings.Decoder decoder0) {
    if (decoder0 == null) {
      return null;
    }
    _FileIoctlParams result = new _FileIoctlParams();

    var mainDataHeader = bindings.Struct.checkVersion(decoder0, kVersions);
    if (mainDataHeader.version >= 0) {
      
      result.request = decoder0.decodeUint32(8);
    }
    if (mainDataHeader.version >= 0) {
      
      result.inValues = decoder0.decodeUint32Array(16, bindings.kArrayNullable, bindings.kUnspecifiedArrayLength);
    }
    return result;
  }

  void encode(bindings.Encoder encoder) {
    var encoder0 = encoder.getStructEncoderAtOffset(kVersions.last);
    const String structName = "_FileIoctlParams";
    String fieldName;
    try {
      fieldName = "request";
      encoder0.encodeUint32(request, 8);
      fieldName = "inValues";
      encoder0.encodeUint32Array(inValues, 16, bindings.kArrayNullable, bindings.kUnspecifiedArrayLength);
    } on bindings.MojoCodecError catch(e) {
      bindings.Struct.fixErrorMessage(e, fieldName, structName);
      rethrow;
    }
  }

  String toString() {
    return "_FileIoctlParams("
           "request: $request" ", "
           "inValues: $inValues" ")";
  }

  Map toJson() {
    Map map = new Map();
    map["request"] = request;
    map["inValues"] = inValues;
    return map;
  }
}


class FileIoctlResponseParams extends bindings.Struct {
  static const List<bindings.StructDataHeader> kVersions = const [
    const bindings.StructDataHeader(24, 0)
  ];
  types_mojom.Error error = null;
  List<int> outValues = null;

  FileIoctlResponseParams() : super(kVersions.last.size);

  FileIoctlResponseParams.init(
    types_mojom.Error this.error, 
    List<int> this.outValues
  ) : super(kVersions.last.size);

  static FileIoctlResponseParams deserialize(bindings.Message message) =>
      bindings.Struct.deserialize(decode, message);

  static FileIoctlResponseParams decode(bindings.Decoder decoder0) {
    if (decoder0 == null) {
      return null;
    }
    FileIoctlResponseParams result = new FileIoctlResponseParams();

    var mainDataHeader = bindings.Struct.checkVersion(decoder0, kVersions);
    if (mainDataHeader.version >= 0) {
      
        result.error = types_mojom.Error.decode(decoder0, 8);
        if (result.error == null) {
          throw new bindings.MojoCodecError(
            'Trying to decode null union for non-nullable types_mojom.Error.');
        }
    }
    if (mainDataHeader.version >= 0) {
      
      result.outValues = decoder0.decodeUint32Array(16, bindings.kArrayNullable, bindings.kUnspecifiedArrayLength);
    }
    return result;
  }

  void encode(bindings.Encoder encoder) {
    var encoder0 = encoder.getStructEncoderAtOffset(kVersions.last);
    const String structName = "FileIoctlResponseParams";
    String fieldName;
    try {
      fieldName = "error";
      encoder0.encodeEnum(error, 8);
      fieldName = "outValues";
      encoder0.encodeUint32Array(outValues, 16, bindings.kArrayNullable, bindings.kUnspecifiedArrayLength);
    } on bindings.MojoCodecError catch(e) {
      bindings.Struct.fixErrorMessage(e, fieldName, structName);
      rethrow;
    }
  }

  String toString() {
    return "FileIoctlResponseParams("
           "error: $error" ", "
           "outValues: $outValues" ")";
  }

  Map toJson() {
    Map map = new Map();
    map["error"] = error;
    map["outValues"] = outValues;
    return map;
  }
}

const int _fileMethodCloseName = 0;
const int _fileMethodReadName = 1;
const int _fileMethodWriteName = 2;
const int _fileMethodReadToStreamName = 3;
const int _fileMethodWriteFromStreamName = 4;
const int _fileMethodTellName = 5;
const int _fileMethodSeekName = 6;
const int _fileMethodStatName = 7;
const int _fileMethodTruncateName = 8;
const int _fileMethodTouchName = 9;
const int _fileMethodDupName = 10;
const int _fileMethodReopenName = 11;
const int _fileMethodAsBufferName = 12;
const int _fileMethodIoctlName = 13;

class _FileServiceDescription implements service_describer.ServiceDescription {
  void getTopLevelInterface(Function responder) {
    responder(null);
  }

  void getTypeDefinition(String typeKey, Function responder) {
    responder(null);
  }

  void getAllTypeDefinitions(Function responder) {
    responder(null);
  }
}

abstract class File {
  static const String serviceName = null;

  static service_describer.ServiceDescription _cachedServiceDescription;
  static service_describer.ServiceDescription get serviceDescription {
    if (_cachedServiceDescription == null) {
      _cachedServiceDescription = new _FileServiceDescription();
    }
    return _cachedServiceDescription;
  }

  static FileProxy connectToService(
      bindings.ServiceConnector s, String url, [String serviceName]) {
    FileProxy p = new FileProxy.unbound();
    String name = serviceName ?? File.serviceName;
    if ((name == null) || name.isEmpty) {
      throw new core.MojoApiError(
          "If an interface has no ServiceName, then one must be provided.");
    }
    s.connectToService(url, p, name);
    return p;
  }
  void close_(void callback(types_mojom.Error err));
  void read(int numBytesToRead,int offset,types_mojom.Whence whence,void callback(types_mojom.Error error, List<int> bytesRead));
  void write(List<int> bytesToWrite,int offset,types_mojom.Whence whence,void callback(types_mojom.Error error, int numBytesWritten));
  void readToStream(core.MojoDataPipeProducer source,int offset,types_mojom.Whence whence,int numBytesToRead,void callback(types_mojom.Error error));
  void writeFromStream(core.MojoDataPipeConsumer sink,int offset,types_mojom.Whence whence,void callback(types_mojom.Error error));
  void tell(void callback(types_mojom.Error error, int position));
  void seek(int offset,types_mojom.Whence whence,void callback(types_mojom.Error error, int position));
  void stat(void callback(types_mojom.Error error, types_mojom.FileInformation fileInformation));
  void truncate(int size,void callback(types_mojom.Error error));
  void touch(types_mojom.TimespecOrNow atime,types_mojom.TimespecOrNow mtime,void callback(types_mojom.Error error));
  void dup(FileInterfaceRequest file,void callback(types_mojom.Error error));
  void reopen(FileInterfaceRequest file,int openFlags,void callback(types_mojom.Error error));
  void asBuffer(void callback(types_mojom.Error error, core.MojoSharedBuffer buffer));
  void ioctl(int request,List<int> inValues,void callback(types_mojom.Error error, List<int> outValues));
}

abstract class FileInterface
    implements bindings.MojoInterface<File>,
               File {
  factory FileInterface([File impl]) =>
      new FileStub.unbound(impl);

  factory FileInterface.fromEndpoint(
      core.MojoMessagePipeEndpoint endpoint,
      [File impl]) =>
      new FileStub.fromEndpoint(endpoint, impl);

  factory FileInterface.fromMock(
      File mock) =>
      new FileProxy.fromMock(mock);
}

abstract class FileInterfaceRequest
    implements bindings.MojoInterface<File>,
               File {
  factory FileInterfaceRequest() =>
      new FileProxy.unbound();
}

class _FileProxyControl
    extends bindings.ProxyMessageHandler
    implements bindings.ProxyControl<File> {
  File impl;

  _FileProxyControl.fromEndpoint(
      core.MojoMessagePipeEndpoint endpoint) : super.fromEndpoint(endpoint);

  _FileProxyControl.fromHandle(
      core.MojoHandle handle) : super.fromHandle(handle);

  _FileProxyControl.unbound() : super.unbound();

  String get serviceName => File.serviceName;

  void handleResponse(bindings.ServiceMessage message) {
    switch (message.header.type) {
      case _fileMethodCloseName:
        var r = FileCloseResponseParams.deserialize(
            message.payload);
        if (!message.header.hasRequestId) {
          proxyError("Expected a message with a valid request Id.");
          return;
        }
        Function callback = callbackMap[message.header.requestId];
        if (callback == null) {
          proxyError(
              "Message had unknown request Id: ${message.header.requestId}");
          return;
        }
        callbackMap.remove(message.header.requestId);
        callback(r.err );
        break;
      case _fileMethodReadName:
        var r = FileReadResponseParams.deserialize(
            message.payload);
        if (!message.header.hasRequestId) {
          proxyError("Expected a message with a valid request Id.");
          return;
        }
        Function callback = callbackMap[message.header.requestId];
        if (callback == null) {
          proxyError(
              "Message had unknown request Id: ${message.header.requestId}");
          return;
        }
        callbackMap.remove(message.header.requestId);
        callback(r.error , r.bytesRead );
        break;
      case _fileMethodWriteName:
        var r = FileWriteResponseParams.deserialize(
            message.payload);
        if (!message.header.hasRequestId) {
          proxyError("Expected a message with a valid request Id.");
          return;
        }
        Function callback = callbackMap[message.header.requestId];
        if (callback == null) {
          proxyError(
              "Message had unknown request Id: ${message.header.requestId}");
          return;
        }
        callbackMap.remove(message.header.requestId);
        callback(r.error , r.numBytesWritten );
        break;
      case _fileMethodReadToStreamName:
        var r = FileReadToStreamResponseParams.deserialize(
            message.payload);
        if (!message.header.hasRequestId) {
          proxyError("Expected a message with a valid request Id.");
          return;
        }
        Function callback = callbackMap[message.header.requestId];
        if (callback == null) {
          proxyError(
              "Message had unknown request Id: ${message.header.requestId}");
          return;
        }
        callbackMap.remove(message.header.requestId);
        callback(r.error );
        break;
      case _fileMethodWriteFromStreamName:
        var r = FileWriteFromStreamResponseParams.deserialize(
            message.payload);
        if (!message.header.hasRequestId) {
          proxyError("Expected a message with a valid request Id.");
          return;
        }
        Function callback = callbackMap[message.header.requestId];
        if (callback == null) {
          proxyError(
              "Message had unknown request Id: ${message.header.requestId}");
          return;
        }
        callbackMap.remove(message.header.requestId);
        callback(r.error );
        break;
      case _fileMethodTellName:
        var r = FileTellResponseParams.deserialize(
            message.payload);
        if (!message.header.hasRequestId) {
          proxyError("Expected a message with a valid request Id.");
          return;
        }
        Function callback = callbackMap[message.header.requestId];
        if (callback == null) {
          proxyError(
              "Message had unknown request Id: ${message.header.requestId}");
          return;
        }
        callbackMap.remove(message.header.requestId);
        callback(r.error , r.position );
        break;
      case _fileMethodSeekName:
        var r = FileSeekResponseParams.deserialize(
            message.payload);
        if (!message.header.hasRequestId) {
          proxyError("Expected a message with a valid request Id.");
          return;
        }
        Function callback = callbackMap[message.header.requestId];
        if (callback == null) {
          proxyError(
              "Message had unknown request Id: ${message.header.requestId}");
          return;
        }
        callbackMap.remove(message.header.requestId);
        callback(r.error , r.position );
        break;
      case _fileMethodStatName:
        var r = FileStatResponseParams.deserialize(
            message.payload);
        if (!message.header.hasRequestId) {
          proxyError("Expected a message with a valid request Id.");
          return;
        }
        Function callback = callbackMap[message.header.requestId];
        if (callback == null) {
          proxyError(
              "Message had unknown request Id: ${message.header.requestId}");
          return;
        }
        callbackMap.remove(message.header.requestId);
        callback(r.error , r.fileInformation );
        break;
      case _fileMethodTruncateName:
        var r = FileTruncateResponseParams.deserialize(
            message.payload);
        if (!message.header.hasRequestId) {
          proxyError("Expected a message with a valid request Id.");
          return;
        }
        Function callback = callbackMap[message.header.requestId];
        if (callback == null) {
          proxyError(
              "Message had unknown request Id: ${message.header.requestId}");
          return;
        }
        callbackMap.remove(message.header.requestId);
        callback(r.error );
        break;
      case _fileMethodTouchName:
        var r = FileTouchResponseParams.deserialize(
            message.payload);
        if (!message.header.hasRequestId) {
          proxyError("Expected a message with a valid request Id.");
          return;
        }
        Function callback = callbackMap[message.header.requestId];
        if (callback == null) {
          proxyError(
              "Message had unknown request Id: ${message.header.requestId}");
          return;
        }
        callbackMap.remove(message.header.requestId);
        callback(r.error );
        break;
      case _fileMethodDupName:
        var r = FileDupResponseParams.deserialize(
            message.payload);
        if (!message.header.hasRequestId) {
          proxyError("Expected a message with a valid request Id.");
          return;
        }
        Function callback = callbackMap[message.header.requestId];
        if (callback == null) {
          proxyError(
              "Message had unknown request Id: ${message.header.requestId}");
          return;
        }
        callbackMap.remove(message.header.requestId);
        callback(r.error );
        break;
      case _fileMethodReopenName:
        var r = FileReopenResponseParams.deserialize(
            message.payload);
        if (!message.header.hasRequestId) {
          proxyError("Expected a message with a valid request Id.");
          return;
        }
        Function callback = callbackMap[message.header.requestId];
        if (callback == null) {
          proxyError(
              "Message had unknown request Id: ${message.header.requestId}");
          return;
        }
        callbackMap.remove(message.header.requestId);
        callback(r.error );
        break;
      case _fileMethodAsBufferName:
        var r = FileAsBufferResponseParams.deserialize(
            message.payload);
        if (!message.header.hasRequestId) {
          proxyError("Expected a message with a valid request Id.");
          return;
        }
        Function callback = callbackMap[message.header.requestId];
        if (callback == null) {
          proxyError(
              "Message had unknown request Id: ${message.header.requestId}");
          return;
        }
        callbackMap.remove(message.header.requestId);
        callback(r.error , r.buffer );
        break;
      case _fileMethodIoctlName:
        var r = FileIoctlResponseParams.deserialize(
            message.payload);
        if (!message.header.hasRequestId) {
          proxyError("Expected a message with a valid request Id.");
          return;
        }
        Function callback = callbackMap[message.header.requestId];
        if (callback == null) {
          proxyError(
              "Message had unknown request Id: ${message.header.requestId}");
          return;
        }
        callbackMap.remove(message.header.requestId);
        callback(r.error , r.outValues );
        break;
      default:
        proxyError("Unexpected message type: ${message.header.type}");
        close(immediate: true);
        break;
    }
  }

  @override
  String toString() {
    var superString = super.toString();
    return "_FileProxyControl($superString)";
  }
}

class FileProxy
    extends bindings.Proxy<File>
    implements File,
               FileInterface,
               FileInterfaceRequest {
  FileProxy.fromEndpoint(
      core.MojoMessagePipeEndpoint endpoint)
      : super(new _FileProxyControl.fromEndpoint(endpoint));

  FileProxy.fromHandle(core.MojoHandle handle)
      : super(new _FileProxyControl.fromHandle(handle));

  FileProxy.unbound()
      : super(new _FileProxyControl.unbound());

  factory FileProxy.fromMock(File mock) {
    FileProxy newMockedProxy =
        new FileProxy.unbound();
    newMockedProxy.impl = mock;
    return newMockedProxy;
  }

  static FileProxy newFromEndpoint(
      core.MojoMessagePipeEndpoint endpoint) {
    assert(endpoint.setDescription("For FileProxy"));
    return new FileProxy.fromEndpoint(endpoint);
  }


  void close_(void callback(types_mojom.Error err)) {
    if (impl != null) {
      impl.close_(callback);
      return;
    }
    var params = new _FileCloseParams();
    Function zonedCallback;
    if (identical(Zone.current, Zone.ROOT)) {
      zonedCallback = callback;
    } else {
      Zone z = Zone.current;
      zonedCallback = ((types_mojom.Error err) {
        z.bindCallback(() {
          callback(err);
        })();
      });
    }
    ctrl.sendMessageWithRequestId(
        params,
        _fileMethodCloseName,
        -1,
        bindings.MessageHeader.kMessageExpectsResponse,
        zonedCallback);
  }
  void read(int numBytesToRead,int offset,types_mojom.Whence whence,void callback(types_mojom.Error error, List<int> bytesRead)) {
    if (impl != null) {
      impl.read(numBytesToRead,offset,whence,callback);
      return;
    }
    var params = new _FileReadParams();
    params.numBytesToRead = numBytesToRead;
    params.offset = offset;
    params.whence = whence;
    Function zonedCallback;
    if (identical(Zone.current, Zone.ROOT)) {
      zonedCallback = callback;
    } else {
      Zone z = Zone.current;
      zonedCallback = ((types_mojom.Error error, List<int> bytesRead) {
        z.bindCallback(() {
          callback(error, bytesRead);
        })();
      });
    }
    ctrl.sendMessageWithRequestId(
        params,
        _fileMethodReadName,
        -1,
        bindings.MessageHeader.kMessageExpectsResponse,
        zonedCallback);
  }
  void write(List<int> bytesToWrite,int offset,types_mojom.Whence whence,void callback(types_mojom.Error error, int numBytesWritten)) {
    if (impl != null) {
      impl.write(bytesToWrite,offset,whence,callback);
      return;
    }
    var params = new _FileWriteParams();
    params.bytesToWrite = bytesToWrite;
    params.offset = offset;
    params.whence = whence;
    Function zonedCallback;
    if (identical(Zone.current, Zone.ROOT)) {
      zonedCallback = callback;
    } else {
      Zone z = Zone.current;
      zonedCallback = ((types_mojom.Error error, int numBytesWritten) {
        z.bindCallback(() {
          callback(error, numBytesWritten);
        })();
      });
    }
    ctrl.sendMessageWithRequestId(
        params,
        _fileMethodWriteName,
        -1,
        bindings.MessageHeader.kMessageExpectsResponse,
        zonedCallback);
  }
  void readToStream(core.MojoDataPipeProducer source,int offset,types_mojom.Whence whence,int numBytesToRead,void callback(types_mojom.Error error)) {
    if (impl != null) {
      impl.readToStream(source,offset,whence,numBytesToRead,callback);
      return;
    }
    var params = new _FileReadToStreamParams();
    params.source = source;
    params.offset = offset;
    params.whence = whence;
    params.numBytesToRead = numBytesToRead;
    Function zonedCallback;
    if (identical(Zone.current, Zone.ROOT)) {
      zonedCallback = callback;
    } else {
      Zone z = Zone.current;
      zonedCallback = ((types_mojom.Error error) {
        z.bindCallback(() {
          callback(error);
        })();
      });
    }
    ctrl.sendMessageWithRequestId(
        params,
        _fileMethodReadToStreamName,
        -1,
        bindings.MessageHeader.kMessageExpectsResponse,
        zonedCallback);
  }
  void writeFromStream(core.MojoDataPipeConsumer sink,int offset,types_mojom.Whence whence,void callback(types_mojom.Error error)) {
    if (impl != null) {
      impl.writeFromStream(sink,offset,whence,callback);
      return;
    }
    var params = new _FileWriteFromStreamParams();
    params.sink = sink;
    params.offset = offset;
    params.whence = whence;
    Function zonedCallback;
    if (identical(Zone.current, Zone.ROOT)) {
      zonedCallback = callback;
    } else {
      Zone z = Zone.current;
      zonedCallback = ((types_mojom.Error error) {
        z.bindCallback(() {
          callback(error);
        })();
      });
    }
    ctrl.sendMessageWithRequestId(
        params,
        _fileMethodWriteFromStreamName,
        -1,
        bindings.MessageHeader.kMessageExpectsResponse,
        zonedCallback);
  }
  void tell(void callback(types_mojom.Error error, int position)) {
    if (impl != null) {
      impl.tell(callback);
      return;
    }
    var params = new _FileTellParams();
    Function zonedCallback;
    if (identical(Zone.current, Zone.ROOT)) {
      zonedCallback = callback;
    } else {
      Zone z = Zone.current;
      zonedCallback = ((types_mojom.Error error, int position) {
        z.bindCallback(() {
          callback(error, position);
        })();
      });
    }
    ctrl.sendMessageWithRequestId(
        params,
        _fileMethodTellName,
        -1,
        bindings.MessageHeader.kMessageExpectsResponse,
        zonedCallback);
  }
  void seek(int offset,types_mojom.Whence whence,void callback(types_mojom.Error error, int position)) {
    if (impl != null) {
      impl.seek(offset,whence,callback);
      return;
    }
    var params = new _FileSeekParams();
    params.offset = offset;
    params.whence = whence;
    Function zonedCallback;
    if (identical(Zone.current, Zone.ROOT)) {
      zonedCallback = callback;
    } else {
      Zone z = Zone.current;
      zonedCallback = ((types_mojom.Error error, int position) {
        z.bindCallback(() {
          callback(error, position);
        })();
      });
    }
    ctrl.sendMessageWithRequestId(
        params,
        _fileMethodSeekName,
        -1,
        bindings.MessageHeader.kMessageExpectsResponse,
        zonedCallback);
  }
  void stat(void callback(types_mojom.Error error, types_mojom.FileInformation fileInformation)) {
    if (impl != null) {
      impl.stat(callback);
      return;
    }
    var params = new _FileStatParams();
    Function zonedCallback;
    if (identical(Zone.current, Zone.ROOT)) {
      zonedCallback = callback;
    } else {
      Zone z = Zone.current;
      zonedCallback = ((types_mojom.Error error, types_mojom.FileInformation fileInformation) {
        z.bindCallback(() {
          callback(error, fileInformation);
        })();
      });
    }
    ctrl.sendMessageWithRequestId(
        params,
        _fileMethodStatName,
        -1,
        bindings.MessageHeader.kMessageExpectsResponse,
        zonedCallback);
  }
  void truncate(int size,void callback(types_mojom.Error error)) {
    if (impl != null) {
      impl.truncate(size,callback);
      return;
    }
    var params = new _FileTruncateParams();
    params.size = size;
    Function zonedCallback;
    if (identical(Zone.current, Zone.ROOT)) {
      zonedCallback = callback;
    } else {
      Zone z = Zone.current;
      zonedCallback = ((types_mojom.Error error) {
        z.bindCallback(() {
          callback(error);
        })();
      });
    }
    ctrl.sendMessageWithRequestId(
        params,
        _fileMethodTruncateName,
        -1,
        bindings.MessageHeader.kMessageExpectsResponse,
        zonedCallback);
  }
  void touch(types_mojom.TimespecOrNow atime,types_mojom.TimespecOrNow mtime,void callback(types_mojom.Error error)) {
    if (impl != null) {
      impl.touch(atime,mtime,callback);
      return;
    }
    var params = new _FileTouchParams();
    params.atime = atime;
    params.mtime = mtime;
    Function zonedCallback;
    if (identical(Zone.current, Zone.ROOT)) {
      zonedCallback = callback;
    } else {
      Zone z = Zone.current;
      zonedCallback = ((types_mojom.Error error) {
        z.bindCallback(() {
          callback(error);
        })();
      });
    }
    ctrl.sendMessageWithRequestId(
        params,
        _fileMethodTouchName,
        -1,
        bindings.MessageHeader.kMessageExpectsResponse,
        zonedCallback);
  }
  void dup(FileInterfaceRequest file,void callback(types_mojom.Error error)) {
    if (impl != null) {
      impl.dup(file,callback);
      return;
    }
    var params = new _FileDupParams();
    params.file = file;
    Function zonedCallback;
    if (identical(Zone.current, Zone.ROOT)) {
      zonedCallback = callback;
    } else {
      Zone z = Zone.current;
      zonedCallback = ((types_mojom.Error error) {
        z.bindCallback(() {
          callback(error);
        })();
      });
    }
    ctrl.sendMessageWithRequestId(
        params,
        _fileMethodDupName,
        -1,
        bindings.MessageHeader.kMessageExpectsResponse,
        zonedCallback);
  }
  void reopen(FileInterfaceRequest file,int openFlags,void callback(types_mojom.Error error)) {
    if (impl != null) {
      impl.reopen(file,openFlags,callback);
      return;
    }
    var params = new _FileReopenParams();
    params.file = file;
    params.openFlags = openFlags;
    Function zonedCallback;
    if (identical(Zone.current, Zone.ROOT)) {
      zonedCallback = callback;
    } else {
      Zone z = Zone.current;
      zonedCallback = ((types_mojom.Error error) {
        z.bindCallback(() {
          callback(error);
        })();
      });
    }
    ctrl.sendMessageWithRequestId(
        params,
        _fileMethodReopenName,
        -1,
        bindings.MessageHeader.kMessageExpectsResponse,
        zonedCallback);
  }
  void asBuffer(void callback(types_mojom.Error error, core.MojoSharedBuffer buffer)) {
    if (impl != null) {
      impl.asBuffer(callback);
      return;
    }
    var params = new _FileAsBufferParams();
    Function zonedCallback;
    if (identical(Zone.current, Zone.ROOT)) {
      zonedCallback = callback;
    } else {
      Zone z = Zone.current;
      zonedCallback = ((types_mojom.Error error, core.MojoSharedBuffer buffer) {
        z.bindCallback(() {
          callback(error, buffer);
        })();
      });
    }
    ctrl.sendMessageWithRequestId(
        params,
        _fileMethodAsBufferName,
        -1,
        bindings.MessageHeader.kMessageExpectsResponse,
        zonedCallback);
  }
  void ioctl(int request,List<int> inValues,void callback(types_mojom.Error error, List<int> outValues)) {
    if (impl != null) {
      impl.ioctl(request,inValues,callback);
      return;
    }
    var params = new _FileIoctlParams();
    params.request = request;
    params.inValues = inValues;
    Function zonedCallback;
    if (identical(Zone.current, Zone.ROOT)) {
      zonedCallback = callback;
    } else {
      Zone z = Zone.current;
      zonedCallback = ((types_mojom.Error error, List<int> outValues) {
        z.bindCallback(() {
          callback(error, outValues);
        })();
      });
    }
    ctrl.sendMessageWithRequestId(
        params,
        _fileMethodIoctlName,
        -1,
        bindings.MessageHeader.kMessageExpectsResponse,
        zonedCallback);
  }
}

class _FileStubControl
    extends bindings.StubMessageHandler
    implements bindings.StubControl<File> {
  File _impl;

  _FileStubControl.fromEndpoint(
      core.MojoMessagePipeEndpoint endpoint, [File impl])
      : super.fromEndpoint(endpoint, autoBegin: impl != null) {
    _impl = impl;
  }

  _FileStubControl.fromHandle(
      core.MojoHandle handle, [File impl])
      : super.fromHandle(handle, autoBegin: impl != null) {
    _impl = impl;
  }

  _FileStubControl.unbound([this._impl]) : super.unbound();

  String get serviceName => File.serviceName;


  Function _fileCloseResponseParamsResponder(
      int requestId) {
  return (types_mojom.Error err) {
      var result = new FileCloseResponseParams();
      result.err = err;
      sendResponse(buildResponseWithId(
          result,
          _fileMethodCloseName,
          requestId,
          bindings.MessageHeader.kMessageIsResponse));
    };
  }
  Function _fileReadResponseParamsResponder(
      int requestId) {
  return (types_mojom.Error error, List<int> bytesRead) {
      var result = new FileReadResponseParams();
      result.error = error;
      result.bytesRead = bytesRead;
      sendResponse(buildResponseWithId(
          result,
          _fileMethodReadName,
          requestId,
          bindings.MessageHeader.kMessageIsResponse));
    };
  }
  Function _fileWriteResponseParamsResponder(
      int requestId) {
  return (types_mojom.Error error, int numBytesWritten) {
      var result = new FileWriteResponseParams();
      result.error = error;
      result.numBytesWritten = numBytesWritten;
      sendResponse(buildResponseWithId(
          result,
          _fileMethodWriteName,
          requestId,
          bindings.MessageHeader.kMessageIsResponse));
    };
  }
  Function _fileReadToStreamResponseParamsResponder(
      int requestId) {
  return (types_mojom.Error error) {
      var result = new FileReadToStreamResponseParams();
      result.error = error;
      sendResponse(buildResponseWithId(
          result,
          _fileMethodReadToStreamName,
          requestId,
          bindings.MessageHeader.kMessageIsResponse));
    };
  }
  Function _fileWriteFromStreamResponseParamsResponder(
      int requestId) {
  return (types_mojom.Error error) {
      var result = new FileWriteFromStreamResponseParams();
      result.error = error;
      sendResponse(buildResponseWithId(
          result,
          _fileMethodWriteFromStreamName,
          requestId,
          bindings.MessageHeader.kMessageIsResponse));
    };
  }
  Function _fileTellResponseParamsResponder(
      int requestId) {
  return (types_mojom.Error error, int position) {
      var result = new FileTellResponseParams();
      result.error = error;
      result.position = position;
      sendResponse(buildResponseWithId(
          result,
          _fileMethodTellName,
          requestId,
          bindings.MessageHeader.kMessageIsResponse));
    };
  }
  Function _fileSeekResponseParamsResponder(
      int requestId) {
  return (types_mojom.Error error, int position) {
      var result = new FileSeekResponseParams();
      result.error = error;
      result.position = position;
      sendResponse(buildResponseWithId(
          result,
          _fileMethodSeekName,
          requestId,
          bindings.MessageHeader.kMessageIsResponse));
    };
  }
  Function _fileStatResponseParamsResponder(
      int requestId) {
  return (types_mojom.Error error, types_mojom.FileInformation fileInformation) {
      var result = new FileStatResponseParams();
      result.error = error;
      result.fileInformation = fileInformation;
      sendResponse(buildResponseWithId(
          result,
          _fileMethodStatName,
          requestId,
          bindings.MessageHeader.kMessageIsResponse));
    };
  }
  Function _fileTruncateResponseParamsResponder(
      int requestId) {
  return (types_mojom.Error error) {
      var result = new FileTruncateResponseParams();
      result.error = error;
      sendResponse(buildResponseWithId(
          result,
          _fileMethodTruncateName,
          requestId,
          bindings.MessageHeader.kMessageIsResponse));
    };
  }
  Function _fileTouchResponseParamsResponder(
      int requestId) {
  return (types_mojom.Error error) {
      var result = new FileTouchResponseParams();
      result.error = error;
      sendResponse(buildResponseWithId(
          result,
          _fileMethodTouchName,
          requestId,
          bindings.MessageHeader.kMessageIsResponse));
    };
  }
  Function _fileDupResponseParamsResponder(
      int requestId) {
  return (types_mojom.Error error) {
      var result = new FileDupResponseParams();
      result.error = error;
      sendResponse(buildResponseWithId(
          result,
          _fileMethodDupName,
          requestId,
          bindings.MessageHeader.kMessageIsResponse));
    };
  }
  Function _fileReopenResponseParamsResponder(
      int requestId) {
  return (types_mojom.Error error) {
      var result = new FileReopenResponseParams();
      result.error = error;
      sendResponse(buildResponseWithId(
          result,
          _fileMethodReopenName,
          requestId,
          bindings.MessageHeader.kMessageIsResponse));
    };
  }
  Function _fileAsBufferResponseParamsResponder(
      int requestId) {
  return (types_mojom.Error error, core.MojoSharedBuffer buffer) {
      var result = new FileAsBufferResponseParams();
      result.error = error;
      result.buffer = buffer;
      sendResponse(buildResponseWithId(
          result,
          _fileMethodAsBufferName,
          requestId,
          bindings.MessageHeader.kMessageIsResponse));
    };
  }
  Function _fileIoctlResponseParamsResponder(
      int requestId) {
  return (types_mojom.Error error, List<int> outValues) {
      var result = new FileIoctlResponseParams();
      result.error = error;
      result.outValues = outValues;
      sendResponse(buildResponseWithId(
          result,
          _fileMethodIoctlName,
          requestId,
          bindings.MessageHeader.kMessageIsResponse));
    };
  }

  void handleMessage(bindings.ServiceMessage message) {
    if (bindings.ControlMessageHandler.isControlMessage(message)) {
      bindings.ControlMessageHandler.handleMessage(
          this, 0, message);
      return;
    }
    if (_impl == null) {
      throw new core.MojoApiError("$this has no implementation set");
    }
    switch (message.header.type) {
      case _fileMethodCloseName:
        _impl.close_(_fileCloseResponseParamsResponder(message.header.requestId));
        break;
      case _fileMethodReadName:
        var params = _FileReadParams.deserialize(
            message.payload);
        _impl.read(params.numBytesToRead, params.offset, params.whence, _fileReadResponseParamsResponder(message.header.requestId));
        break;
      case _fileMethodWriteName:
        var params = _FileWriteParams.deserialize(
            message.payload);
        _impl.write(params.bytesToWrite, params.offset, params.whence, _fileWriteResponseParamsResponder(message.header.requestId));
        break;
      case _fileMethodReadToStreamName:
        var params = _FileReadToStreamParams.deserialize(
            message.payload);
        _impl.readToStream(params.source, params.offset, params.whence, params.numBytesToRead, _fileReadToStreamResponseParamsResponder(message.header.requestId));
        break;
      case _fileMethodWriteFromStreamName:
        var params = _FileWriteFromStreamParams.deserialize(
            message.payload);
        _impl.writeFromStream(params.sink, params.offset, params.whence, _fileWriteFromStreamResponseParamsResponder(message.header.requestId));
        break;
      case _fileMethodTellName:
        _impl.tell(_fileTellResponseParamsResponder(message.header.requestId));
        break;
      case _fileMethodSeekName:
        var params = _FileSeekParams.deserialize(
            message.payload);
        _impl.seek(params.offset, params.whence, _fileSeekResponseParamsResponder(message.header.requestId));
        break;
      case _fileMethodStatName:
        _impl.stat(_fileStatResponseParamsResponder(message.header.requestId));
        break;
      case _fileMethodTruncateName:
        var params = _FileTruncateParams.deserialize(
            message.payload);
        _impl.truncate(params.size, _fileTruncateResponseParamsResponder(message.header.requestId));
        break;
      case _fileMethodTouchName:
        var params = _FileTouchParams.deserialize(
            message.payload);
        _impl.touch(params.atime, params.mtime, _fileTouchResponseParamsResponder(message.header.requestId));
        break;
      case _fileMethodDupName:
        var params = _FileDupParams.deserialize(
            message.payload);
        _impl.dup(params.file, _fileDupResponseParamsResponder(message.header.requestId));
        break;
      case _fileMethodReopenName:
        var params = _FileReopenParams.deserialize(
            message.payload);
        _impl.reopen(params.file, params.openFlags, _fileReopenResponseParamsResponder(message.header.requestId));
        break;
      case _fileMethodAsBufferName:
        _impl.asBuffer(_fileAsBufferResponseParamsResponder(message.header.requestId));
        break;
      case _fileMethodIoctlName:
        var params = _FileIoctlParams.deserialize(
            message.payload);
        _impl.ioctl(params.request, params.inValues, _fileIoctlResponseParamsResponder(message.header.requestId));
        break;
      default:
        throw new bindings.MojoCodecError("Unexpected message name");
        break;
    }
  }

  File get impl => _impl;
  set impl(File d) {
    if (d == null) {
      throw new core.MojoApiError("$this: Cannot set a null implementation");
    }
    if (isBound && (_impl == null)) {
      beginHandlingEvents();
    }
    _impl = d;
  }

  @override
  void bind(core.MojoMessagePipeEndpoint endpoint) {
    super.bind(endpoint);
    if (!isOpen && (_impl != null)) {
      beginHandlingEvents();
    }
  }

  @override
  String toString() {
    var superString = super.toString();
    return "_FileStubControl($superString)";
  }

  int get version => 0;
}

class FileStub
    extends bindings.Stub<File>
    implements File,
               FileInterface,
               FileInterfaceRequest {
  FileStub.unbound([File impl])
      : super(new _FileStubControl.unbound(impl));

  FileStub.fromEndpoint(
      core.MojoMessagePipeEndpoint endpoint, [File impl])
      : super(new _FileStubControl.fromEndpoint(endpoint, impl));

  FileStub.fromHandle(
      core.MojoHandle handle, [File impl])
      : super(new _FileStubControl.fromHandle(handle, impl));

  static FileStub newFromEndpoint(
      core.MojoMessagePipeEndpoint endpoint) {
    assert(endpoint.setDescription("For FileStub"));
    return new FileStub.fromEndpoint(endpoint);
  }


  void close_(void callback(types_mojom.Error err)) {
    return impl.close_(callback);
  }
  void read(int numBytesToRead,int offset,types_mojom.Whence whence,void callback(types_mojom.Error error, List<int> bytesRead)) {
    return impl.read(numBytesToRead,offset,whence,callback);
  }
  void write(List<int> bytesToWrite,int offset,types_mojom.Whence whence,void callback(types_mojom.Error error, int numBytesWritten)) {
    return impl.write(bytesToWrite,offset,whence,callback);
  }
  void readToStream(core.MojoDataPipeProducer source,int offset,types_mojom.Whence whence,int numBytesToRead,void callback(types_mojom.Error error)) {
    return impl.readToStream(source,offset,whence,numBytesToRead,callback);
  }
  void writeFromStream(core.MojoDataPipeConsumer sink,int offset,types_mojom.Whence whence,void callback(types_mojom.Error error)) {
    return impl.writeFromStream(sink,offset,whence,callback);
  }
  void tell(void callback(types_mojom.Error error, int position)) {
    return impl.tell(callback);
  }
  void seek(int offset,types_mojom.Whence whence,void callback(types_mojom.Error error, int position)) {
    return impl.seek(offset,whence,callback);
  }
  void stat(void callback(types_mojom.Error error, types_mojom.FileInformation fileInformation)) {
    return impl.stat(callback);
  }
  void truncate(int size,void callback(types_mojom.Error error)) {
    return impl.truncate(size,callback);
  }
  void touch(types_mojom.TimespecOrNow atime,types_mojom.TimespecOrNow mtime,void callback(types_mojom.Error error)) {
    return impl.touch(atime,mtime,callback);
  }
  void dup(FileInterfaceRequest file,void callback(types_mojom.Error error)) {
    return impl.dup(file,callback);
  }
  void reopen(FileInterfaceRequest file,int openFlags,void callback(types_mojom.Error error)) {
    return impl.reopen(file,openFlags,callback);
  }
  void asBuffer(void callback(types_mojom.Error error, core.MojoSharedBuffer buffer)) {
    return impl.asBuffer(callback);
  }
  void ioctl(int request,List<int> inValues,void callback(types_mojom.Error error, List<int> outValues)) {
    return impl.ioctl(request,inValues,callback);
  }
}



